#!/usr/bin/env python3

import sys
import command_line
import flatland_REF


if __name__ == "__main__":
    # Parse the command line args
    args = command_line.parse(sys.argv[1:])
    flatland_REF.create_canvas(args)
