#!/usr/bin/env python3

import sys
import command_line
from canvas import Canvas

args = command_line.parse(sys.argv[1:])

flatland_canvas = Canvas(diagram_type=args.diagram, standard_sheet_name=args.sheet, orientation=args.orientation)

output_file_name = args.file # Empty if standard output chosen

print(flatland_canvas)
print(flatland_canvas.Diagram)

# Draw diagram on canvas with file name